title: Chris Blunt Codes
description: Updates on my projects
markdown: kramdown

remote_theme: jekyll/minima

minima:
  skin: dark

show_excerpts: true

future: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-remote-theme

social_links:
  - { platform: github, user_url: "https://github.com/chrisblunt-codes" }
  - { platform: email,  user_url: "mailto:contact@chrisblunt.codes" }
