title: Chris Blunt Codes
description: Updates on my projects
theme: minima
markdown: kramdown

minima:
  skin: dark

show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar

social_links:
  - { platform: github, user_url: "https://github.com/chrisblunt-codes" }
  - { platform: email,  user_url: "mailto:contact@chrisblunt.codes" }
